// <auto-generated />
namespace ProductStore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class deletecolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletecolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201301031248385_deletecolumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
